#ifndef DEFINE_H
#define DEFINE_H

#define BYTE unsigned char
#define DWORD unsigned int




#define SIGNATURE_MOVE 0         // 4
#define SIGNATURE_SIZE 4
#define MACHINE_MOVE 4
#define MACHINE_SIZE 2
#define NUMBEROFSESSIONS_MOVE 6  // 2
#define NUMBEROFSESSIONS_SIZE 2
#define TIMEDATESTAMP_MOVE 8     // 4
#define TIMEDATESTAMP_SIZE 4
#define POINTEROFSYMBOLTABLE_MOVE 12
#define POINTEROFSYMBOLTABLE_SIZE 4
#define NUMBEROFSYMBOLS_MOVE 16
#define NUMBEROFSYMBOLS_SIZE 4
#define SIZEOFOPTIONALHEADER_MOVE 20
#define SIZEOFOPTIONALHEADER_SIZE 2
#define CHARACTERISTICS_MOVE 22
#define CHARACTERISTICS_SIZE 2

#define MAGIC_MOVE 24
#define MAGIC_SIZE 2
#define MAJORLINKERVERSION_MOVE 26
#define MAJORLINKERVERSION_SIZE 1
#define MINORLINKERVERSION_MOVE 27
#define MINORLINKERVERSION_SIZE 28

#endif // DEFINE_H

