#ifndef DEFINE_H
#define DEFINE_H

#define BYTE unsigned char
#define DWORD unsigned int




#define SIGNATURE_MOVE 0         // 4
#define SIGNATURE_SIZE 4
#define MACHINE_MOVE 4
#define MACHINE_SIZE 2
#define NUMBEROFSESSIONS_MOVE 6  // 2
#define NUMBEROFSESSIONS_SIZE 2
#define TIMEDATESTAMP_MOVE 8     // 4
#define TIMEDATESTAMP_SIZE 4
#define POINTEROFSYMBOLTABLE_MOVE 12
#define POINTEROFSYMBOLTABLE_SIZE 4
#define NUMBEROFSYMBOLS_MOVE 16
#define NUMBEROFSYMBOLS_SIZE 4
#define SIZEOFOPTIONALHEADER_MOVE 20
#define SIZEOFOPTIONALHEADER_SIZE 2
#define CHARACTERISTICS_MOVE 22
#define CHARACTERISTICS_SIZE 2

#define MAGIC_MOVE 24
#define MAGIC_SIZE 2
#define MAJORLINKERVERSION_MOVE 26
#define MAJORLINKERVERSION_SIZE 1
#define MINORLINKERVERSION_MOVE 27
#define MINORLINKERVERSION_SIZE 1
#define SIZEOFCODE_MOVE 28
#define SIZEOFCODE_SIZE 4
#define SIZEOFINITIALIZEDDATA_MOVE 32
#define SIZEOFINITIALIZEDDATA_SIZE 4
#define SIZEOFUNINITIALIZEDDATA_MOVE 36
#define SIZEOFUNINITIALIZEDDATA_SIZE 4
#define ADDRESSOFENTRYPOINT_MOVE 40
#define ADDRESSOFENTRYPOINT_SIZE 4
#define BASEOFCODE_MOVE 44
#define BASEOFCODE_SIZE 4
#define BASEOFDATA_MOVE 48
#define BASEOFDATA_SIZE 4
#define IMAGEBASE_MOVE 52
#define IMAGEBASE_SIZE 4
#define SECTIONALIGNMENT_MOVE 56
#define SECTIONALIGNMENT_SIZE 4
#define FILEALIGNMENT_MOVE 60
#define FILEALIGNMENT_SIZE 4
#define MAJOROPERATINGSYSTEMVERSION_MOVE 66
#define MAJOROPERATINGSYSTEMVERSION_SIZE 2
#define MINOROPERATINGSYSTEMVERSION_MOVE 68
#define MINOROPERATINGSYSTEMVERSION_SIZE 2
#define MAJORIMAGEVERSION_MOVE 70
#define MAJORIMAGEVERSION_SIZE 2
#define MINORIMAGEVERSION_MOVE 72
#define MINORIMAGEVERSION_SIZE 2
#define MAJORSUBSYSTEMVERSION_MOVE 74
#define MAJORSUBSYSTEMVERSION_SIZE 2
#define MINORSUBSYSTEMVERSION_MOVE 76
#define MINORSUBSYSTEMVERSION_SIZE 2
#define WIN32VERSIONVALUE_MOVE 78
#define WIN32VERSIONVALUE_SIZE 4
#define SIZEOFIMAGE_MOVE 82
#define SiZEOFIMAGE_SIZE 4
#define SIZEOFHEADERS_MOVE 86
#define SIZEOFHEADERS_SIZE 4
#define CHECKSUM_MOVE 90
#define CHECKSUM_SIZE 4
#define SUBSYSTEM_MOVE 94
#define SUBSYSTEM_SIZE 4
#define DLLCHARACTERISTICS_MOVE 98
#define DLLCHARACTERISTICS_SIZE 2
#define SIZEOFSTACKRESERVER_MOVE 100
#define SIZEOFSTACKRESERVER_SIZE 4
#define SIZEOFSTACKCOMMIT_MOVE 104
#define SIZEOFSTACKCOMMIT_SIZE 4
#define SIZEOFHEAPRESERVE_MOVE 108
#define SIZEOFHEAPRESERVE_SIZE 4
#define SIZEOFHEAPCOMMIT_MOVE 112
#define SIZEOFHEAPCOMMIT_SIZE 4
#define LOADERFLAGS_MOVE 116
#define LOADERFLAGS_SIZE 4
#define NUMBEROFRVANDSIZES_MOVE 120
#define NUMVEROFRVAnDSIZES_SIZE 4
#define DATAIRECTORY_MOVE 124
#define DATAIRECTORY_SIZE 0x80


#endif // DEFINE_H

